### ISSUE TITLE
Tentative list of projects

### ISSUE THREAD

**Issue by japaric** [rust-embedded/showcase#1]
This repository is the implementation of rust-embedded/wg#187.

As discussed in the last meeting we'll use this issue to collect a list of projects that *could* be part of the showcase.

cc @rust-embedded/resources @adamgreig @cr1901

**Comment by therealprof** [comment]
https://github.com/ah-/anne-key

**Comment by therealprof** [comment]
https://www.tockos.org/

**Comment by therealprof** [comment]
https://github.com/thejpster/monotron

**Comment by thejpster** [comment]
There's more Monotron at https://twitter.com/therealjpster and http://railwayelectronics.blogspot.com/

**Comment by therealprof** [comment]
https://blog.florencepaul.com/

**Comment by gbip** [comment]
> 
> 
> https://blog.florencepaul.com/

I can provide a bit more information on this, but the projet is not yet ready for showcase. Tell me if you need some picture or anything else : we have some nice Embedded in Rust stickers :wink:

**Comment by Frederik-Baetens** [comment]
Not my project, but I thought it looked cool https://github.com/smbolton/stm32f3-oscilloscope

**Comment by mathk** [comment]
Here are list of my project not very finished but still usable. If that could be a way to have great feedback I would be happy:

1.  MFX STM IO expansion  /IDD Measurement device crate. Only idd is supported for the time being:
https://github.com/mathk/mfxstm32l152 

2. I2c-tool-hal to have better abstraction when using i2c. For the time being it only help to convert basic u32(24)/16/6 type:
https://github.com/mathk/i2c-hal-tools

**Comment by japaric** [comment]
You can all start [submitting projects](https://github.com/rust-embedded/showcase#submit-your-project) now! (Note that you need some picture / video of your project). So I'm going to close this issue in favor of PRs by project authors. cc @texitoi @ah-
