### ISSUE TITLE
Website mockup

### ISSUE THREAD

**Issue by japaric** [rust-embedded/showcase#2]
I made a website mockup. You should be able to see it rendered [here]. I've also included some screenshots at the bottom of this comment.

All kind of feedback is welcomed.

If you are all happy with it I can make a PR setting up a static site generator.

[here]: https://japaric.github.io/stunning-waffle/index.html

Some notes:

- The background color is the color of the WG logo.

- Images and videos always have 4:3 aspect ratio.

- Videos should be .mp4; Chrome doesn't like .webm. (Firefox for Android seems to prefer .webm though)

- Width of images and videos should not be greater than 900px (there is no benefit in having larger images because they'll be shrunk)

- Project description should be short or the text will overflow with some resolutions; 1 paragraph with a max of 280 characters (tweet size) is about the limit

- I've tested that the site behaves the same on Firefox and on Chrome, and I doubt that it displays correctly in IE.

- I'm open to suggestions about what the menu should contain (currently it has HOME, ABOUT and SUBMIT)

- The project names are anchor links, e.g. [anchor to the second project](https://japaric.github.io/stunning-waffle/index.html#lorem-ipsum)

- The author names should link to their website / GH profile page.

- LEARN MORE should link to the project website / GH repository.

- Clicking an image should take you to the project website / GH repository. However, videos don't have that behavior otherwise the video controls wouldn't work.

### Mobile view

![screen shot 2018-11-21 at 16 54 47](https://user-images.githubusercontent.com/5018213/48854331-ee6e4b00-edb1-11e8-8149-efd5e03cdbf0.png)

### Desktop view

[Full page image](https://i.imgur.com/mZVwA6e.png)

**Comment by japaric** [comment]
cc @rust-embedded/resources

**Comment by thejpster** [comment]
Lgtm!

**Comment by osterwood** [comment]
FYI - on Safari the fonts show with serifs due to the font selector.  I recommend the following CSS change in **main.css line 113** : `font-family: Fira Sans, sans;` to `font-family: 'Fira Sans', sans-serif;`

![screen shot 2018-11-27 at 10 56 13 am](https://user-images.githubusercontent.com/10534/49094152-8dbc9380-f233-11e8-8702-cfdff54fd06d.png)

**Comment by therealprof** [comment]
Very nice.

**Comment by korken89** [comment]
I like it!
